app/apps/reporting/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from reporting.views import ReportList, ReportDetail, QuotasLeaderboard


urlpatterns = [
    path('quotas/', ReportList.as_view(), name='report-list'),
    path('quotas/<int:pk>/', ReportDetail.as_view(), name='report-detail'),
    path('quotas/instance/', staff_member_required(QuotasLeaderboard.as_view()), name='quotas-leaderboard'),
]

app/escriptorium/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('reporting.urls')),
    path('api/', include('api.urls', namespace='api')),
    path(r'captcha/', include('captcha.urls')),
    path('', include('django_prometheus.urls')),
]

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

    # simulates a 500 to test error logging
    from django.views.defaults import server_error
    urlpatterns += [path('500/', server_error),
                    path('404/', TemplateView.as_view(template_name='404.html'))]


    # Serve static files in development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/reporting/models.py
from datetime import datetime, timezone

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class TaskReport(models.Model):
    WORKFLOW_STATE_QUEUED = 0
    WORKFLOW_STATE_STARTED = 1
    WORKFLOW_STATE_ERROR = 2
    WORKFLOW_STATE_DONE = 3
    WORKFLOW_STATE_CHOICES = (
        (WORKFLOW_STATE_QUEUED, _("Queued")),
        (WORKFLOW_STATE_STARTED, _("Running")),
        (WORKFLOW_STATE_ERROR, _("Crashed")),
        (WORKFLOW_STATE_DONE, _("Finished"))
    )

    workflow_state = models.PositiveSmallIntegerField(
        default=WORKFLOW_STATE_QUEUED,
        choices=WORKFLOW_STATE_CHOICES
    )
    label = models.CharField(max_length=256)
    messages = models.TextField(blank=True)

    queued_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(null=True)
    done_at = models.DateTimeField(null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # celery task id
    task_id = models.CharField(max_length=64, blank=True, null=True)

    # shared_task method name
    method = models.CharField(max_length=512, blank=True, null=True)

    cpu_cost = models.FloatField(blank=True, null=True)
    gpu_cost = models.FloatField(blank=True, null=True)

    def append(self, text):
        self.messages += text + '\n'

    @property
    def uri(self):
        return reverse('report-detail', kwargs={'pk': self.pk})

    def start(self, task_id, method):
        self.task_id = task_id
        self.method = method
        self.workflow_state = self.WORKFLOW_STATE_STARTED
        self.started_at = datetime.now(timezone.utc)
        self.save()

    def error(self, message):
        # unrecoverable error
        self.workflow_state = self.WORKFLOW_STATE_ERROR
        self.done_at = datetime.now(timezone.utc)
        self.append(message)
        self.save()

    def end(self, extra_links=None):
        self.workflow_state = self.WORKFLOW_STATE_DONE
        self.done_at = datetime.now(timezone.utc)
        self.save()

    def calc_cpu_cost(self, nb_cores):
        task_duration = (self.done_at - self.started_at).total_seconds()
        self.cpu_cost = (task_duration * nb_cores * settings.CPU_COST_FACTOR) / 60
        self.save()

    def calc_gpu_cost(self):
        task_duration = (self.done_at - self.started_at).total_seconds()
        self.gpu_cost = (task_duration * settings.GPU_COST) / 60
        self.save()

app/apps/reporting/views.py
from datetime import date, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, DurationField, ExpressionWrapper, F, Q, Sum
from django.db.models.expressions import OuterRef, Subquery
from django.db.models.fields import IntegerField
from django.views.generic import ListView, DetailView

from reporting.models import TaskReport
from users.models import User


class ReportList(LoginRequiredMixin, ListView):
    model = TaskReport
    paginate_by = 20

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        today = date.today()
        qs = self.request.user.taskreport_set.filter(
            started_at__gte=today - timedelta(days=30)
        ).aggregate(Sum('cpu_cost'), Sum('gpu_cost'))
        context['cpu_cost_last_month'] = qs['cpu_cost__sum'] or 0
        context['gpu_cost_last_month'] = qs['gpu_cost__sum'] or 0
        return context

    def get_queryset(self):
        qs = super().get_queryset()

        blacklist = [
            'core.tasks.lossless_compression',
            'core.tasks.convert',
            'core.tasks.generate_part_thumbnails',
            'users.tasks.async_email',
            'core.tasks.recalculate_masks'
        ]

        return (qs.filter(user=self.request.user)
                  .exclude(method__in=blacklist)
                  .annotate(duration=ExpressionWrapper(F('done_at') - F('started_at'),
                                                       output_field=DurationField()))
                  .order_by('-queued_at'))


class ReportDetail(LoginRequiredMixin, DetailView):
    model = TaskReport
    context_object_name = 'report'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)


class QuotasLeaderboard(LoginRequiredMixin, ListView):
    model = User
    template_name = "reporting/quotas_leaderboard.html"
    paginate_by = 20

    def get_queryset(self):
        qs = super().get_queryset()
        today = date.today()
        filter_last_month = Q(taskreport__started_at__gte=today - timedelta(days=30))
        filter_last_week = Q(taskreport__started_at__gte=today - timedelta(days=7))
        filter_last_day = Q(taskreport__started_at__gte=today - timedelta(days=1))
        runtime = ExpressionWrapper(
            F('taskreport__done_at') - F('taskreport__started_at'),
            output_field=DurationField()
        )

        results = list(
            qs.annotate(
                total_cpu_usage=Sum('taskreport__cpu_cost'),
                total_gpu_usage=Sum('taskreport__gpu_cost'),
                last_month_cpu_usage=Sum('taskreport__cpu_cost', filter=filter_last_month),
                last_month_gpu_usage=Sum('taskreport__gpu_cost', filter=filter_last_month),
                total_tasks=Count('taskreport'),
                total_runtime=Sum(runtime),
                last_week_tasks=Count('taskreport', filter=filter_last_week),
                last_week_runtime=Sum(runtime, filter=filter_last_week),
                last_day_tasks=Count('taskreport', filter=filter_last_day),
                last_day_runtime=Sum(runtime, filter=filter_last_day)
            ).order_by(F('total_runtime').desc(nulls_last=True))
        )
        disk_usages_left = dict(qs.values('id').annotate(disk_usage=Sum('ocrmodel__file_size')).values_list('id', 'disk_usage'))
        disk_usages_right = dict(qs.values('id').annotate(disk_usage=Sum('document__parts__image_file_size')).values_list('id', 'disk_usage'))

        for user in results:
            user.disk_usage = (disk_usages_left[user.id] or 0) + (disk_usages_right[user.id] or 0)

        return results

app/escriptorium/templates/reporting/quotas_leaderboard.html
{% extends "base.html" %}
{% load i18n static timedelta %}

{% block body %}
<div>
  <table class="table table-hover">
    <tr>
      <th colspan="5"></th>
      <th colspan="2" class="text-center">
        <span class="badge badge-pill badge-primary">{% trans "Total" %}</span>
      </th>
      <th colspan="2" class="text-center">
        <span class="badge badge-pill badge-info">{% trans "Last week" %}</span>
      </th>
      <th colspan="2" class="text-center">
        <span class="badge badge-pill badge-success">{% trans "Last day" %}</span>
      </th>
    </tr>
    <tr>
      <th>{% trans "User ID" %}</th>
      <th>{% trans "Username" %}</th>
      <th>{% trans "Disk usage" %}</th>
      <th>{% trans "CPU usage" %}</th>
      <th>{% trans "GPU usage" %}</th>
      <th>{% trans "No. of tasks" %}</th>
      <th>{% trans "Runtime" %}</th>
      <th>{% trans "No. of tasks" %}</th>
      <th>{% trans "Runtime" %}</th>
      <th>{% trans "No. of tasks" %}</th>
      <th>{% trans "Runtime" %}</th>
    </tr>
    {% for user in object_list %}
    <tr>
      <td>{{ user.id }}</td>
      <td>{{ user.username }}</td>
      <td>{{ user.disk_usage|filesizeformat }}</td>
      <td>
          <span title="{% trans "Last month" %}">{{ user.last_month_cpu_usage|default_if_none:0|floatformat:2 }} CPU/min</span>
          <br>
          <small title="{% trans "All time" %}">(total {{ user.total_cpu_usage|default_if_none:0|floatformat:2 }} CPU/min)</small>
      </td>
      <td>
          <span title="{% trans "Last month" %}">{{ user.last_month_gpu_usage|default_if_none:0|floatformat:2 }} GPU/min</span>
          <br>
          <small title="{% trans "All time" %}">(total {{ user.total_gpu_usage|default_if_none:0|floatformat:2 }} GPU/min)</small>
      </td>
      <td>{{ user.total_tasks }}</td>
      <td>{{ user.total_runtime|format_timedelta }}</td>
      <td>{{ user.last_week_tasks }}</td>
      <td>{{ user.last_week_runtime|format_timedelta }}</td>
      <td>{{ user.last_day_tasks }}</td>
      <td>{{ user.last_day_runtime|format_timedelta }}</td>
    </tr>
    {% endfor %}
  </table>

  {% include 'includes/pagination.html' %}
</div>
{% endblock %}

app/escriptorium/templates/reporting/taskreport_detail.html
{% extends "base.html" %}
{% load i18n static %}

{% block body %}
<div>
    <h5>{{ report.label }}</h5>
    <div>{% trans "Status:" %} {{ report.get_workflow_state_display }}</div>
    <div>{% trans "Queued at:" %} {{ report.queued_at }}</div>
    {% if report.workflow_state > 0 %}<div>{% trans "Started at:" %} {{ report.queued_at }}</div>{% endif %}
    {% if report.workflow_state > 1 %}<div>{% trans "Ended at:" %} {{ report.done_at }}</div>{% endif %}
    <div>{% trans "CPU usage" %}: {{ report.cpu_cost }}</div>
    <div>{% trans "GPU usage" %}: {{ report.gpu_cost }}</div>
    {% if report.messages %}<div class="jumbotron">{{ report.messages|linebreaks }}</div>{% endif %}
</div>
{% endblock %}

app/escriptorium/templates/reporting/taskreport_list.html
{% extends "base.html" %}
{% load i18n static timedelta %}

{% block body %}
<div>
    <div class="row mt-4 mb-4">
        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    {% trans "Disk usage" %}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ user.calc_disk_usage|filesizeformat }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans "Calculated from your images and models" %}</h6>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    {% trans "CPU usage" %}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ cpu_cost_last_month|floatformat:3 }} CPU-min</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans "CPU usage over the last month" %}</h6>

                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    {% trans "GPU usage" %}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ gpu_cost_last_month|floatformat:3 }} GPU-min</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans "GPU usage over the last month" %}</h6>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-hover">
        <tr>
            <th>{% trans "Task report" %}</th>
            <th>{% trans "Started at" %}</th>
            <th>{% trans "Done at" %}</th>
            <th>{% trans "Duration" %}</th>
            <th>{% trans "State" %}</th>
            <th>{% trans "CPU cost" %}</th>
            <th>{% trans "GPU cost" %}</th>
            <th></th>
        </tr>
        {% for report in object_list %}
        <tr>
            <td>{{ report.label }}</td>
            <td>{{ report.started_at }}</td>
            <td>{{ report.done_at }}</td>
            <td>{{ report.duration|format_timedelta }}</td>
            <td>
                {% with state=report.get_workflow_state_display %}
                {% if state == "Finished" %}
                <span class="badge badge-pill badge-success">{{ state }}</span>
                {% elif state == "Crashed" %}
                <span class="badge badge-pill badge-danger">{{ state }}</span>
                {% elif state == "Running" %}
                <span class="badge badge-pill badge-primary">{{ state }}</span>
                {% else %}
                <span class="badge badge-pill badge-secondary">{{ state }}</span>
                {% endif %}
                {% endwith %}
            </td>
            <td>
                {% if report.cpu_cost %}
                {{ report.cpu_cost|floatformat:2 }}
                {% else %}
                0
                {% endif %}
                CPU-min
            </td>
            <td>
                {% if report.gpu_cost %}
                {{ report.gpu_cost|floatformat:2 }}
                {% else %}
                0
                {% endif %}
                GPU-min
            </td>
            <td><a href="{% url 'report-detail' report.pk %}">{% trans "Details" %}</a></td>
        </tr>
        {% empty %}
        <tr><td>{% trans "You don't have any task report yet." %}</td></tr>
        {% endfor %}
    </table>

    {% include 'includes/pagination.html' %}
</div>
{% endblock %}